### ISSUE TITLE
cv2 version?

### ISSUE THREAD

**Issue by ron5569** [achalddave/segment-any-moving#6]
Hey
cv2 is not in the requiement.txt
What should be the right version?
I'm asking since i'm facing with the error:

10:12:01 log.py:  51: Writing log file to /segment-any-moving-pytorch/output/appearance/tracks/tracker_Mar01-10-12-01.log
fatal: Not a git repository: git-state/../.git/modules/git-state
fatal: 'git status --porcelain' failed in submodule detectron_pytorch
fatal: Not a git repository: git-state/../.git/modules/git-state
fatal: 'git status --porcelain' failed in submodule detectron_pytorch
Traceback (most recent call last):                                                                                                                                                    | 0/1 [00:00<?, ?it/s]
  File "tracker/track_multiple.py", line 147, in <module>                                                                                                                | 70/1999 [00:00<00:08, 225.37it/s]
    main()
  File "tracker/track_multiple.py", line 143, in main
    output_track_file=None)
  File "/segment-any-moving-pytorch/tracker/track.py", line 1046, in track_and_visualize
    progress=progress)
  File "/segment-any-moving-pytorch/tracker/track.py", line 841, in visualize_tracks
    visualized = visualize_image(t)
  File "/segment-any-moving-pytorch/tracker/track.py", line 811, in visualize_image
    vis_label=vis_label)
  File "/segment-any-moving-pytorch/tracker/track.py", line 558, in visualize_detections
    border_thick=3)
  File "/segment-any-moving-pytorch/utils/vis.py", line 86, in vis_mask
    mask.copy(), cv2.RETR_CCOMP, cv2.CHAIN_APPROX_NONE)
ValueError: not enough values to unpack (expected 3, got 2)
Traceback (most recent call last):
  File "release/custom/track.py", line 80, in <module>
    main()
  File "release/custom/track.py", line 76, in main
    subprocess_call(cmd)
  File "/segment-any-moving-pytorch/release/helpers/misc.py", line 23, in subprocess_call
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'tracker/track_multiple.py', '--images-dir', '/segment-any-moving-pytorch/input', '--detections-dir', '/segment-any-moving-pytorch/output/appearance/detections', '--output-dir', '/segment-any-moving-pytorch/output/appearance/tracks', '--save-numpy', 'True', '--save-images', 'False', '--save-video', 'True', '--bidirectional', '--score-init-min', '0.9', '--fps', '30', '--filename-format', 'frame', '--quiet']' returned non-zero exit status 1.
Traceback (most recent call last):
  File "release/custom/run.py", line 72, in <module>
    main()
  File "release/custom/run.py", line 66, in main
    '--output-dir', tracks_dir
  File "/segment-any-moving-pytorch/release/helpers/misc.py", line 23, in subprocess_call
    subprocess.check_call(cmd, **kwargs)
  File "/usr/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['python', 'release/custom/track.py', '--frames-dir', '/segment-any-moving-pytorch/input', '--detections-dir', '/segment-any-moving-pytorch/output/appearance/detections', '--filename-format', 'frame', '--config', '/segment-any-moving-pytorch/release/config.yaml', '--model', 'appearance', '--output-dir', '/segment-any-moving-pytorch/output/appearance/tracks']' returned non-zero exit status 1.

Thanks!

**Comment by achalddave** [comment]
Sorry about that, my virtual environment has 3.1.0. Hopefully that helps!
